version: "3.8"

services:
  openai_model_wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Pass the OpenAI API key as an environment variable
    volumes:
      - ./app:/app


networks:
  shared_network:
    external: true