version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app  
    environment:
      APP_ENV: development
      PYTHONPATH: /app  
