version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app  
    environment:
      APP_ENV: development
      PYTHONPATH: /app  
    networks:
      - shared_network

  backend_tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend/app:/app
      - ./backend/tests:/app/tests
    environment:
      PYTHONPATH: /app
    command: pytest /app/tests
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    name: shared_network  # This ensures the network is explicitly named
