version: "3.9"

services:
  sql-executor-api:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  
    environment:
      APP_ENV: development
      PYTHONPATH: /app  
    networks:
      - shared_network

  backend_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app
      - ./tests:/app/tests
    environment:
      PYTHONPATH: /app
    command: pytest /app/tests
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    name: shared_network 
