version: '3.8'

services:
  jupyter:
    image: sql-executor-poc
    build: .
    ports:
      - "8888:8888"
    environment:
      - JDBC_DRIVER_PATH=/usr/local/share/postgresql/postgresql-42.7.3.jar
    volumes:
      - .:/home/nimbly-dev/work
    command: ["start-notebook.sh", "--NotebookApp.token=''"]