
LLM_GENERATION_CATEGORY_KEY = "LLM_GENERATION"
EXTERNAL_JWT_AUTH_CATEGORY_KEY = "EXTERNAL_JWT_AUTH"
POST_PROCESS_QUERYSCOPE_CATEGORY_KEY = "POST_PROCESS_QUERYSCOPE"
SCHEMA_RESOLVER_CATEGORY_KEY = "SCHEMA_RESOLVER"