version: "3.9"
services:
  external-login-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - PYTHONPATH=/app
    volumes:
      - ./app:/app

